apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-starter
  namespace: knative-starter
spec:
  template:
    spec:
      containers:
        - name: knative-starter
          image: "{{ .Values.image.repository }}/{{ .Values.image.tag | default .Chart.AppVersion }}"
          envFrom:
            - secretRef:
                name: knative-starter-secret
          env:
            - name: TARGET
              value: "KNative Starter"