apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-starter
  namespace: knative-starter
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: knative-starter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: TARGET
              value: "KNative Starter"
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: knative-starter
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: knative-starter-inbound
  namespace: knative-starter
spec:
  broker: default
  filter:
    attributes:
      type: inbound
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: knative-starter
    uri: /inbound
---
#apiVersion: sources.knative.dev/v1
#kind: SinkBinding
#metadata:
#  name: knative-starter-outbound
#spec:
#  subject:
#    apiVersion: v1
#    kind: Service
#    selector:
#      matchLabels:
#        <label-key>: <label-value>
#  sink:
#    ref:
#      apiVersion: serving.knative.dev/v1
#      kind: Service
#      name: <sink>
#---
#apiVersion: sources.knative.dev/v1beta1
#kind: KafkaSource
#metadata:
#  name: kafka-source
#spec:
#  bootstrapServers: "{{ .Values.kafka.bootstrapServers }}"
#  topics:
#    - output-events
#  sink:
#    ref:
#      apiVersion: serving.knative.dev/v1
#      kind: Service
#      name: knative-starter
#    uri: /customers/reserve
apiVersion: bindings.knative.dev/v1beta1
kind: KafkaBinding
metadata:
  name: kafka-binding-knative-starter
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: knative-starter
  bootstrapServers: "{{ .Values.kafka.bootstrapServers }}"
---
# here, we "mock" another service receiving an event
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  bootstrapServers: "{{ .Values.kafka.bootstrapServers }}"
  topics:
    - starter-events
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: knative-starter
    uri: /loopback